# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(240, 320)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 30, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_exit = QtWidgets.QPushButton(Dialog)
        self.btn_exit.setGeometry(QtCore.QRect(70, 270, 112, 32))
        self.btn_exit.setObjectName("btn_exit")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 192, 114))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_user = QtWidgets.QCommandLinkButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_user.setFont(font)
        self.btn_user.setObjectName("btn_user")
        self.verticalLayout.addWidget(self.btn_user)
        self.btn_flight = QtWidgets.QCommandLinkButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_flight.setFont(font)
        self.btn_flight.setObjectName("btn_flight")
        self.verticalLayout.addWidget(self.btn_flight)
        self.btn_order = QtWidgets.QCommandLinkButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.btn_order.setFont(font)
        self.btn_order.setObjectName("btn_order")
        self.verticalLayout.addWidget(self.btn_order)

        self.retranslateUi(Dialog)
        self.btn_exit.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "信息管理后台"))
        self.label.setText(_translate("Dialog", "管理员，请选择"))
        self.btn_exit.setText(_translate("Dialog", "退出"))
        self.btn_user.setText(_translate("Dialog", "管理用户信息"))
        self.btn_flight.setText(_translate("Dialog", "管理航班信息"))
        self.btn_order.setText(_translate("Dialog", "管理订单信息"))
