# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personal_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_return = QtWidgets.QPushButton(Dialog)
        self.btn_return.setGeometry(QtCore.QRect(110, 200, 112, 32))
        self.btn_return.setObjectName("btn_return")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 241, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.output_username = QtWidgets.QLabel(self.layoutWidget)
        self.output_username.setText("")
        self.output_username.setObjectName("output_username")
        self.gridLayout.addWidget(self.output_username, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.output_email = QtWidgets.QLabel(self.layoutWidget)
        self.output_email.setText("")
        self.output_email.setObjectName("output_email")
        self.gridLayout.addWidget(self.output_email, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.output_tel = QtWidgets.QLabel(self.layoutWidget)
        self.output_tel.setText("")
        self.output_tel.setObjectName("output_tel")
        self.gridLayout.addWidget(self.output_tel, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 160, 301, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_email = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_email.setObjectName("btn_email")
        self.horizontalLayout.addWidget(self.btn_email)
        self.btn_tel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_tel.setObjectName("btn_tel")
        self.horizontalLayout.addWidget(self.btn_tel)
        self.btn_password = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_password.setObjectName("btn_password")
        self.horizontalLayout.addWidget(self.btn_password)

        self.retranslateUi(Dialog)
        self.btn_return.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "个人信息管理"))
        self.label.setText(_translate("Dialog", "个人信息管理"))
        self.btn_return.setText(_translate("Dialog", "返回"))
        self.label_2.setText(_translate("Dialog", "账号："))
        self.label_3.setText(_translate("Dialog", "邮箱："))
        self.label_4.setText(_translate("Dialog", "电话："))
        self.btn_email.setText(_translate("Dialog", "修改邮箱"))
        self.btn_tel.setText(_translate("Dialog", "修改电话"))
        self.btn_password.setText(_translate("Dialog", "修改密码"))
