# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql, username_error, password_error,signup_succ
from PyQt5.QtWidgets import QApplication, QMainWindow, QDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 240)
        self.btn = QtWidgets.QDialogButtonBox(Dialog)
        self.btn.setGeometry(QtCore.QRect(10, 200, 301, 32))
        self.btn.setOrientation(QtCore.Qt.Horizontal)
        self.btn.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.btn.setObjectName("btn")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 30, 193, 147))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.input_user = QtWidgets.QLineEdit(self.widget)
        self.input_user.setObjectName("input_user")
        self.gridLayout.addWidget(self.input_user, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.input_password = QtWidgets.QLineEdit(self.widget)
        self.input_password.setObjectName("input_password")
        self.gridLayout.addWidget(self.input_password, 1, 1, 1, 1)
        self.input_password2 = QtWidgets.QLineEdit(self.widget)
        self.input_password2.setObjectName("input_password2")
        self.gridLayout.addWidget(self.input_password2, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.input_email = QtWidgets.QLineEdit(self.widget)
        self.input_email.setObjectName("input_email")
        self.gridLayout.addWidget(self.input_email, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.input_tel = QtWidgets.QLineEdit(self.widget)
        self.input_tel.setObjectName("input_tel")
        self.gridLayout.addWidget(self.input_tel, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.btn.rejected.connect(Dialog.reject)
        self.btn.accepted.connect(lambda:self.signup_check(Dialog))
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "注册页"))
        self.label.setText(_translate("Dialog", "请输入账号"))
        self.label_2.setText(_translate("Dialog", "请输入密码"))
        self.label_4.setText(_translate("Dialog", "请输入邮箱"))
        self.label_5.setText(_translate("Dialog", "请输入电话"))
        self.label_3.setText(_translate("Dialog", "请确认密码"))

    def signup_check(self,Dialog):
        user = self.input_user.text()
        password = self.input_password.text()
        password2 = self.input_password2.text()
        email = self.input_email.text()
        tel = self.input_tel.text()

        con = pymysql.connect('localhost', 'root', '123456', 'mydb')
        cur = con.cursor()
        cur.execute("select UID from User where UID='" + user + "'")

        Dialog_username_error = QDialog()
        error_username = username_error.Ui_Dialog()
        error_username.setupUi(Dialog_username_error)

        Dialog_password_error = QDialog()
        error_password = password_error.Ui_Dialog()
        error_password.setupUi(Dialog_password_error)

        Dialog_signup_succ=QDialog()
        succ_signup=signup_succ.Ui_Dialog()
        succ_signup.setupUi(Dialog_signup_succ)

        if (cur.rowcount != 0):
            Dialog_username_error.exec()
            cur.close()
        elif (password != password2):
            Dialog_password_error.exec()
            cur.close()
        else:
            cur.execute(
                "insert into User (UID,UPassword,UEmail,UTel) "
                "values ('" + user + "','" + password + "','" + email + "','" + tel + "')")
            con.commit()
            cur.close()
            Dialog_signup_succ.exec()
            Dialog.close()