# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visitor_operation.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QStringListModel
import pymysql

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(673, 489)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.results_flight = QtWidgets.QScrollArea(self.centralwidget)
        self.results_flight.setGeometry(QtCore.QRect(30, 150, 621, 231))
        self.results_flight.setWidgetResizable(True)
        self.results_flight.setObjectName("results_flight")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.verticalScrollBar.setGeometry(QtCore.QRect(600, 0, 16, 231))
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.listView = QtWidgets.QListView(self.scrollAreaWidgetContents)
        self.listView.setGeometry(QtCore.QRect(0, 20, 601, 211))
        self.listView.setObjectName("listView")
        self.results_flight.setWidget(self.scrollAreaWidgetContents)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(420, 210, 3, 61))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 621, 124))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_FID = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_FID.setObjectName("input_FID")
        self.verticalLayout.addWidget(self.input_FID)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.input_Airline = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Airline.setObjectName("input_Airline")
        self.verticalLayout_2.addWidget(self.input_Airline)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.input_Depart = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Depart.setObjectName("input_Depart")
        self.verticalLayout_3.addWidget(self.input_Depart)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.input_Arrive = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Arrive.setObjectName("input_Arrive")
        self.verticalLayout_4.addWidget(self.input_Arrive)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 3, 1, 1)
        self.btn_search = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_search.setObjectName("btn_search")
        self.gridLayout.addWidget(self.btn_search, 2, 1, 1, 2)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(580, 394, 69, 32))
        self.btn_exit.setObjectName("btn_exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.btn_exit.clicked.connect(MainWindow.close)
        self.btn_search.clicked.connect(self.inquire)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.qList = []

    def inquire(self):
        sql_inquire = "select FID,Airline,Depart,Arrive,Dtime,Atime from Flight "
        first = 1
        str_FID = self.input_FID.text()
        str_Airline = self.input_Airline.text()
        str_Depart = self.input_Depart.text()
        str_Arrive = self.input_Arrive.text()

        if str_FID != '':
            if first != 1:
                sql_inquire += " and"
            else:
                sql_inquire += " where "
            sql_inquire += " FID='" + str_FID + "'"
            first = 0
        if str_Airline != '':
            if first != 1:
                sql_inquire += " and"
            else:
                sql_inquire += " where "
            sql_inquire += " Airline like '%" + str_Airline + "%'"
            first = 0
        if str_Depart != '':
            if first != 1:
                sql_inquire += " and"
            else:
                sql_inquire += " where "
            sql_inquire += " Depart like '%" + str_Depart + "%'"
            first = 0
        if str_Arrive != '':
            if first != 1:
                sql_inquire += " and"
            else:
                sql_inquire += " where "
            sql_inquire += " Arrive like '%" + str_Arrive + "%'"
            first = 0

        con = pymysql.connect('localhost', 'root', '123456', 'mydb')
        cur = con.cursor()
        cur.execute(sql_inquire)
        row = cur.fetchone()
        self.qList.clear()
        while row:
            self.qList.append(row[0] + "\t" + row[1] + "\t" + row[2] + "\t" + row[3] + "\t" + row[4] + "\t" + row[5])
            row = cur.fetchone()
        cur.close()
        slm = QStringListModel()
        slm.setStringList(self.qList)
        self.listView.setModel(slm)
        self.statusbar.showMessage('查询成功', 1000)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "用户操作页"))
        self.label_5.setText(_translate("MainWindow", "航班查询"))
        self.label.setText(_translate("MainWindow", "航班号"))
        self.label_2.setText(_translate("MainWindow", "航空公司"))
        self.label_3.setText(_translate("MainWindow", "出发机场"))
        self.label_4.setText(_translate("MainWindow", "到达机场"))
        self.btn_search.setText(_translate("MainWindow", "查询"))
        self.btn_exit.setText(_translate("MainWindow", "退出"))
